### ISSUE TITLE
updating from 0.1c to 0.1d - dispatcher does not start

### ISSUE THREAD

**Issue by dmd** [hermes-router/hermes#12]
If you update from a working 0.1c install to 0.1d, the dispatcher will not start:

```
ImportError: No module named redis
```

**Comment by joshy** [comment]
Hi, you need to install Redis (best install with default settings).  Maybe I should have written an Upgrade statement. I was not sure if anyone is actually using it. Please also note there is a new systemd service which needs to be installed hermes_dispatcher_worker and startet. I needed to change the architecture because we are dispatching too many series which the old architecture couldn‘t handle. If you encounter any other issues please contact me, I will try to resolve them as quickly as possible.

Best regards,
Joshy
--

**Comment by dmd** [comment]
Hmm - given that it's working just fine for us in 0.1c I think maybe I'll just keep it there for the time being. Is 0.2 (or whatever you're going to call it) still in development? Is this project still active?

**Comment by joshy** [comment]
If it is working for you, than better stay at 0.1c. The project is not dead but I guess it is kind of maintenance mode. If you encounter any bugs it will be fixed. 

About 0.2 it is not clear if it will happen. For me version 0.1c is working fine again and features in 0.2 are nice to have but for now not critical.


--

**Comment by joshy** [comment]
Added [upgrade notes.](https://github.com/hermes-router/hermes/releases/tag/0.1d)
